const USER_SELECT_VILLAINS = "USER_SELECT_VILLAINS"
const RANDOM_SELECT_VILLAINS = "RANDOM_SELECT_VILLAINS"
const CHANGE_VILLAIN = "CHANGE_VILLAIN"
const USER_SELECT_HEROS = "USER_SELECT_HEROS"
const RANDOM_SELECT_HEROS = "RANDOM_SELECT_HEROS"
const CHANGE_HERO = "CHANGE_HERO"
const USER_SELECT_LOCATION = "USER_SELECT_LOCATION"
const RANDOM_SELECT_LOCATIONS = "RANDOM_SELECT_LOCATIONS"

export {
  USER_SELECT_VILLAINS,
  RANDOM_SELECT_VILLAINS,
  CHANGE_VILLAIN,
  USER_SELECT_HEROS,
  RANDOM_SELECT_HEROS,
  CHANGE_HERO,
  USER_SELECT_LOCATION,
  RANDOM_SELECT_LOCATIONS,
}
